import type { Tile } from "../types/mahjong"

export const TILES: Tile[] = [
  // Bamboo tiles (B) - Row 1, Columns 0-8
  {
    id: 'B1',
    suit: 'B',
    rank: 1,
    isHonor: false,
    isFlower: false,
    displayName: 'Bamboo 1',
    imgX: 0,
    imgY: 1,
  },
  {
    id: 'B2',
    suit: 'B',
    rank: 2,
    isHonor: false,
    isFlower: false,
    displayName: 'Bamboo 2',
    imgX: 1,
    imgY: 1,
  },
  {
    id: 'B3',
    suit: 'B',
    rank: 3,
    isHonor: false,
    isFlower: false,
    displayName: 'Bamboo 3',
    imgX: 2,
    imgY: 1,
  },
  {
    id: 'B4',
    suit: 'B',
    rank: 4,
    isHonor: false,
    isFlower: false,
    displayName: 'Bamboo 4',
    imgX: 3,
    imgY: 1,
  },
  {
    id: 'B5',
    suit: 'B',
    rank: 5,
    isHonor: false,
    isFlower: false,
    displayName: 'Bamboo 5',
    imgX: 4,
    imgY: 1,
  },
  {
    id: 'B6',
    suit: 'B',
    rank: 6,
    isHonor: false,
    isFlower: false,
    displayName: 'Bamboo 6',
    imgX: 5,
    imgY: 1,
  },
  {
    id: 'B7',
    suit: 'B',
    rank: 7,
    isHonor: false,
    isFlower: false,
    displayName: 'Bamboo 7',
    imgX: 6,
    imgY: 1,
  },
  {
    id: 'B8',
    suit: 'B',
    rank: 8,
    isHonor: false,
    isFlower: false,
    displayName: 'Bamboo 8',
    imgX: 7,
    imgY: 1,
  },
  {
    id: 'B9',
    suit: 'B',
    rank: 9,
    isHonor: false,
    isFlower: false,
    displayName: 'Bamboo 9',
    imgX: 8,
    imgY: 1,
  },

  // Character tiles (C) - Row 2, Columns 0-8
  {
    id: 'C1',
    suit: 'C',
    rank: 1,
    isHonor: false,
    isFlower: false,
    displayName: 'Character 1',
    imgX: 0,
    imgY: 2,
  },
  {
    id: 'C2',
    suit: 'C',
    rank: 2,
    isHonor: false,
    isFlower: false,
    displayName: 'Character 2',
    imgX: 1,
    imgY: 2,
  },
  {
    id: 'C3',
    suit: 'C',
    rank: 3,
    isHonor: false,
    isFlower: false,
    displayName: 'Character 3',
    imgX: 2,
    imgY: 2,
  },
  {
    id: 'C4',
    suit: 'C',
    rank: 4,
    isHonor: false,
    isFlower: false,
    displayName: 'Character 4',
    imgX: 3,
    imgY: 2,
  },
  {
    id: 'C5',
    suit: 'C',
    rank: 5,
    isHonor: false,
    isFlower: false,
    displayName: 'Character 5',
    imgX: 4,
    imgY: 2,
  },
  {
    id: 'C6',
    suit: 'C',
    rank: 6,
    isHonor: false,
    isFlower: false,
    displayName: 'Character 6',
    imgX: 5,
    imgY: 2,
  },
  {
    id: 'C7',
    suit: 'C',
    rank: 7,
    isHonor: false,
    isFlower: false,
    displayName: 'Character 7',
    imgX: 6,
    imgY: 2,
  },
  {
    id: 'C8',
    suit: 'C',
    rank: 8,
    isHonor: false,
    isFlower: false,
    displayName: 'Character 8',
    imgX: 7,
    imgY: 2,
  },
  {
    id: 'C9',
    suit: 'C',
    rank: 9,
    isHonor: false,
    isFlower: false,
    displayName: 'Character 9',
    imgX: 8,
    imgY: 2,
  },

  // Dot tiles (D) - Row 0, Columns 0-8
  {
    id: 'D1',
    suit: 'D',
    rank: 1,
    isHonor: false,
    isFlower: false,
    displayName: 'Dot 1',
    imgX: 0,
    imgY: 0,
  },
  {
    id: 'D2',
    suit: 'D',
    rank: 2,
    isHonor: false,
    isFlower: false,
    displayName: 'Dot 2',
    imgX: 1,
    imgY: 0,
  },
  {
    id: 'D3',
    suit: 'D',
    rank: 3,
    isHonor: false,
    isFlower: false,
    displayName: 'Dot 3',
    imgX: 2,
    imgY: 0,
  },
  {
    id: 'D4',
    suit: 'D',
    rank: 4,
    isHonor: false,
    isFlower: false,
    displayName: 'Dot 4',
    imgX: 3,
    imgY: 0,
  },
  {
    id: 'D5',
    suit: 'D',
    rank: 5,
    isHonor: false,
    isFlower: false,
    displayName: 'Dot 5',
    imgX: 4,
    imgY: 0,
  },
  {
    id: 'D6',
    suit: 'D',
    rank: 6,
    isHonor: false,
    isFlower: false,
    displayName: 'Dot 6',
    imgX: 5,
    imgY: 0,
  },
  {
    id: 'D7',
    suit: 'D',
    rank: 7,
    isHonor: false,
    isFlower: false,
    displayName: 'Dot 7',
    imgX: 6,
    imgY: 0,
  },
  {
    id: 'D8',
    suit: 'D',
    rank: 8,
    isHonor: false,
    isFlower: false,
    displayName: 'Dot 8',
    imgX: 7,
    imgY: 0,
  },
  {
    id: 'D9',
    suit: 'D',
    rank: 9,
    isHonor: false,
    isFlower: false,
    displayName: 'Dot 9',
    imgX: 8,
    imgY: 0,
  },

  // Wind tiles (W) - Row 3, Columns 0-3
  {
    id: 'WE',
    suit: 'W',
    rank: 1,
    isHonor: true,
    isFlower: false,
    displayName: 'East Wind',
    imgX: 0,
    imgY: 3,
  },
  {
    id: 'WS',
    suit: 'W',
    rank: 2,
    isHonor: true,
    isFlower: false,
    displayName: 'South Wind',
    imgX: 1,
    imgY: 3,
  },
  {
    id: 'WW',
    suit: 'W',
    rank: 3,
    isHonor: true,
    isFlower: false,
    displayName: 'West Wind',
    imgX: 2,
    imgY: 3,
  },
  {
    id: 'WN',
    suit: 'W',
    rank: 4,
    isHonor: true,
    isFlower: false,
    displayName: 'North Wind',
    imgX: 3,
    imgY: 3,
  },

  // Dragon tiles (d) - Row 3, Columns 4-6
  {
    id: 'dR',
    suit: 'd',
    rank: 1,
    isHonor: true,
    isFlower: false,
    displayName: 'Red Dragon',
    imgX: 4,
    imgY: 3,
  },
  {
    id: 'dG',
    suit: 'd',
    rank: 2,
    isHonor: true,
    isFlower: false,
    displayName: 'Green Dragon',
    imgX: 5,
    imgY: 3,
  },
  {
    id: 'dW',
    suit: 'd',
    rank: 3,
    isHonor: true,
    isFlower: false,
    displayName: 'White Dragon',
    imgX: 6,
    imgY: 3,
  },

  // Flower tiles (F) - Row 4, Columns 0-3
  {
    id: 'F1',
    suit: 'F',
    rank: 1,
    isHonor: false,
    isFlower: true,
    displayName: 'Plum Blossom',
    imgX: 0,
    imgY: 4,
  },
  {
    id: 'F2',
    suit: 'F',
    rank: 2,
    isHonor: false,
    isFlower: true,
    displayName: 'Orchid',
    imgX: 1,
    imgY: 4,
  },
  {
    id: 'F3',
    suit: 'F',
    rank: 3,
    isHonor: false,
    isFlower: true,
    displayName: 'Chrysanthemum',
    imgX: 2,
    imgY: 4,
  },
  {
    id: 'F4',
    suit: 'F',
    rank: 4,
    isHonor: false,
    isFlower: true,
    displayName: 'Bamboo',
    imgX: 3,
    imgY: 4,
  },

  // Season tiles (S) - Row 4, Columns 4-7
  {
    id: 'S1',
    suit: 'S',
    rank: 1,
    isHonor: false,
    isFlower: true,
    displayName: 'Spring',
    imgX: 4,
    imgY: 4,
  },
  {
    id: 'S2',
    suit: 'S',
    rank: 2,
    isHonor: false,
    isFlower: true,
    displayName: 'Summer',
    imgX: 5,
    imgY: 4,
  },
  {
    id: 'S3',
    suit: 'S',
    rank: 3,
    isHonor: false,
    isFlower: true,
    displayName: 'Autumn',
    imgX: 6,
    imgY: 4,
  },
  {
    id: 'S4',
    suit: 'S',
    rank: 4,
    isHonor: false,
    isFlower: true,
    displayName: 'Winter',
    imgX: 7,
    imgY: 4,
  },
]